export const appConfig = {
  default_schema_identifier: "public",
  default_migrations_folder: __dirname + "/../database/migrations",
  default_seeders_folder: __dirname + "/../database/seeders",
  tenant_migrations_folder: __dirname + "/../database/tenant_migrations",
  tenant_seeders_folder: __dirname + "/../database/tenant_seeders",
  recommended_bcrypt_rounds: 12,
  // env,
  // getStockTradeContract,
  // getProvider,
  // metamaskNetworkArgs,
  // getERC20Contract,
  // getStockTradeAddress,
  // FeeAmount,
  // TICK_SPACINGS,
  // getNonFungibleTokenContract,
  // getSwapFactoryContract,
  // getQuoterContract,
  // getSwapRouterContract,
  // getPredefinedVotingContract,
  // getGenericVotingContract,
  // getBaseVotingTypedContract,
  // getSwchAddress,
  // getBaseVotingContract,
};
